site_name: Horilla Docs
site_description: Dokumentasi modular Horilla HRMS (Arsitektur, Admin, User, RBAC, Security, AI, API)
site_url: https://bontiharyanto.github.io/horiladoc/

# saat dev lokal, sebaiknya kosongkan atau komentari site_url
# site_url: https://example.com/horilla-docs
# ganti ke repo kamu sendiri kalau ini docs di repo kamu
repo_url: https://github.com/bontiharyanto/horiladoc
repo_name: bontiharyanto/horiladoc
edit_uri: "edit/main/docs/"

docs_dir: docs
dev_addr: 127.0.0.1:8085

theme:
  name: material
  language: id
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mode gelap
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mode terang

nav:
  - Home: index.md
  - Arsitektur: 01-arsitektur.md
  - System Administrator: 02-system-administrator.md
  - Panduan User: 03-user-guide.md

  - Modul Pengguna:
      - Recruitment: user/user-recruitment.md
      - Onboarding: user/user-onboarding.md
      - Employee Management: user/user-employee-management.md
      - Attendance Tracking: user/user-attendance-tracking.md
      - Leave Management: user/user-leave-management.md
      - Asset Management: user/user-asset-management.md
      - Payroll: user/user-payroll.md
      - Performance Management: user/user-performance-management.md
      - Offboarding: user/user-offboarding.md
      - Helpdesk: user/user-helpdesk.md
      - Calendar: user/user-calendar.md
      - Project Management: user/user-project-management.md

  - "Modul Admin":
      - Recruitment (Admin): admin/admin-recruitment.md
      - Onboarding (Admin): admin/admin-onboarding.md
      - Employee Management (Admin): admin/admin-employee-management.md
      - Attendance Tracking (Admin): admin/admin-attendance-tracking.md
      - Leave Management (Admin): admin/admin-leave-management.md
      - Asset Management (Admin): admin/admin-asset-management.md
      - Payroll (Admin): admin/admin-payroll.md
      - Performance Management (Admin): admin/admin-performance-management.md
      - Offboarding (Admin): admin/admin-offboarding.md
      - Helpdesk (Admin): admin/admin-helpdesk.md
      - Calendar (Admin/Beta): admin/admin-calendar.md
      - Project Management (Admin/Beta): admin/admin-project-management.md

  - RBAC & CRUD: 04-rbac-crud.md
  - Security: 05-security.md
  - Integrasi AI: 06-ai-integration.md
  - API: 07-api.md




plugins:
  - search
  # - autorefs   # aktifkan kalau sudah di-inject: pipx inject mkdocs mkdocs-autorefs
  # - mermaid2   # aktifkan kalau mau diagram mermaid

plugins:
  - search

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:        # <— HANYA SEKALI
      custom_fences:
        - name: mermaid          # fence ```mermaid
          class: mermaid         # akan jadi <div class="mermaid">…</div>
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/mermaid-shim.js


